In [1]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5])

arr1 = np.array([[1,2,3],
                [4,5,6]])

print(arr)
print(arr.ndim)  #dimension
#indexing
print(arr[2])
#change the value of index 
arr[2] = 50
print(arr)



print(arr1)
print(arr1.ndim)

#indexing
print(arr1[0][2])
#change the value of index 
arr1[1][0] = 7
print(arr1)



[1 2 3 4 5]
1
3
[ 1  2 50  4  5]
[[1 2 3]
 [4 5 6]]
2
3
[[1 2 3]
 [7 5 6]]


##slicing

In [17]:
#slicing (start,end and step) 
print(arr)
#1d array slicing
arr_mod = arr[0:3]
print(arr_mod)


[ 1  2 50  4  5]
[ 1  2 50]


In [25]:
#2d array slicing

#print(arr1)

row_0 = arr1[0:1 ,]
print(row_0)

row_1 = arr1[1: ,]
print(row_1)

row_2 = arr1[1: ,1:3]
print(row_2)


[[1 2 3]]
[[7 5 6]]
[[5 6]]


In [30]:
arr3 = np.arange(1,10).reshape(3,3)
print(arr3)

#slicing 

row_4 = arr3[1:, 1:3]
print(row_4)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]


#Advance indexing and slicing

In [38]:
print(arr)

[1 0 0 0 5]


Advance indexing and slicing

In [8]:
adv_arr = np.array([1,2,3,4,5])
print(adv_arr)
adv_arr[2] = 20
print(adv_arr[0:4])

[1 2 3 4 5]
[ 1  2 20  4]


In [10]:
lst = np.array([10,20,30,40,50])

values = lst[[3,4]]

print(values)

[40 50]


In [24]:
arr_1 = np.arange(1,10,1).reshape(3,3) 
print(arr_1)
print(arr_1[[1,2],[0,1]])
#advance
print(arr_1[arr_1 >2])
#2 theke jara boro tader man 0 kore dive
arr_1[arr_1 > 2] = 0
print(arr_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 8]
[3 4 5 6 7 8 9]
[[1 2 0]
 [0 0 0]
 [0 0 0]]
