In [1]:
import numpy as np 
arr = np.array([1,2,3])
arr = arr * 5
print(arr)

[ 5 10 15]


ND array

In [8]:
import numpy as np 
arr =np.array([1,2,3,4,5]) #one demansional array 
print(type(arr))
print(arr.ndim)

#2d array 

arr1 = np.array([[1,2,3],
                [4,5,6]])

print(arr1.ndim)

#3d array 



<class 'numpy.ndarray'>
1
2


Array attribute

In [11]:
#dimension 
print(arr.ndim)
print(arr1.ndim)

#shape
print(arr.shape)
print(arr1.shape)

# size 
print(arr.size)
print(arr1.size)

1
2
(5,)
(2, 3)
5
6


ndarray data type

In [12]:
arr = np.array ([1,2,3,4,5])

print(arr.dtype)

int64


In [14]:
arr1 = np.array([1,2,3,4.5]) # upcasting in array 

print(arr1.dtype)

arr1 = np.array([1,2,3,4.5,'5']) 
print(arr1.dtype)

float64
<U32


Seletcing a data type for a array

arr = np.array([1,2,3],dtype =np.int8)  #Here a datatype converted into a int8 datatypes 
print(arr.dtype)

In [19]:
arr = np.array([1,2,3])
print(arr.dtype)

arr = arr.astype(np.int32)
print(arr)                        #converting data into 64 bytes to 32 bytes
print(arr.dtype)



int64
[1 2 3]
int32


Nd array creating from exiting data

In [7]:
#list 
import numpy as np

lst = [10,20,40,50.5]
arr = np.array(lst, dtype = np.int32)
print(arr)
print(type(arr))
print(arr.dtype)




[10 20 40 50]
<class 'numpy.ndarray'>
int32


In [9]:
mixed_list =[10,10.5,True,'Hello']

arr = np.array(mixed_list)

print(arr)
print(type(arr))
print(arr.dtype)

['10' '10.5' 'True' 'Hello']
<class 'numpy.ndarray'>
<U32


In [13]:
matrix =[[1,2,3],
        [4,5,6]]

arr = np.array(matrix)

print(arr)
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
2
int64
(2, 3)


In [16]:
#tuple
tple =(1,2,3)

arr = np.array(tple)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
1
int64
(3,)


In [21]:
#set 
st = {1,2,3}
arr = np.array(list(st))
arr = arr.astype(np.int32)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)

[1 2 3]
<class 'numpy.ndarray'>
1
int32
(3,)


In [28]:
#Dictionary 
dc ={'a': 10,'b': 20,'c': 30}
keys = dc.keys()
values = dc.values()


#keys to ndarray

arr = np.array(list(keys))
print(arr)
print(type(arr))
#values to ndarry
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
3
