Array creation with random values

In [1]:
import numpy as np

In [4]:
#random values 

arr = np.random.rand(2,3)

print(arr)
print(arr.dtype)

[[0.62083169 0.69827101 0.10458882]
 [0.01634104 0.3734796  0.37087537]]
float64


Random integer value generator

In [10]:
arr = np.random.randint(1,10 ,(10,10))      #random int values(star,end,shape)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)

[[2 8 6 7 3 3 9 3 9 8]
 [3 1 9 3 9 8 8 4 2 2]
 [2 9 7 4 7 3 6 8 4 2]
 [5 7 1 1 4 8 2 3 5 9]
 [3 8 5 1 1 1 5 8 1 3]
 [6 6 4 4 8 9 2 3 9 4]
 [9 4 4 8 8 7 3 3 7 6]
 [1 8 4 8 3 7 7 1 1 1]
 [2 5 6 4 5 6 3 5 5 4]
 [7 3 9 2 6 6 8 8 2 2]]
(10, 10)
int32
2


Floating type values creation

In [13]:
#Floating type values creation
arr = np.random.uniform(30,40,(5,5))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[[31.86595091 30.20386885 34.21187289 38.66080678 30.26901545]
 [38.54807518 35.43148936 36.33519251 36.74861541 38.19357545]
 [32.51019767 32.52665485 32.54149717 39.56161874 33.36307935]
 [39.72178781 32.39944063 36.5221841  36.60739541 31.57210205]
 [33.19663382 31.33346128 33.11707053 31.21168183 38.58544862]]
<class 'numpy.ndarray'>
float64
(5, 5)


Array creation with range

In [16]:
arr = np.arange(1,10,1) .reshape(3 ,3)  #start end and steps 

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(3, 3)


Linespace in Numpy

In [15]:
# np.linespace (start,end and koyta point pick korbo)
arr = np.linspace(1,10,5)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)

[ 1.    3.25  5.5   7.75 10.  ]
<class 'numpy.ndarray'>
float64
(5,)


Logspace in Numpy

In [14]:
#np.logspace  (start,End(included),koyta values nAttributeError)

arr = np.logspace(0,4,5)
print(arr)

[1.e+00 1.e+01 1.e+02 1.e+03 1.e+04]
