Creating a matrix for linear algebra

In [1]:
import numpy as np

In [4]:
diagonal_mattrix =np.diag([1,2,3,5,6])
print(diagonal_mattrix)
print(diagonal_mattrix.shape)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 5 0]
 [0 0 0 0 6]]
(5, 5)


identity matrix

In [6]:
identity_mat = np.eye(3)
print(identity_mat)
print(identity_mat.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [9]:
#np.eye(row,coulmn and k value)
mat =np.eye(3,4,-1)
print(mat)
mat =np.eye(3,4,1)
print(mat)

[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
