In [7]:
import numpy as np
arr = np.zeros((1,3),dtype = np.int16)
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.size)
print(arr.dtype)

[[0 0 0]]
<class 'numpy.ndarray'>
2
3
int16


In [13]:
arr1 =[[[1,2,3],
       [4,5,6]],

       [[5,6,7],
      [4,7,8]],

       [[2,7,9],
      [8,0,3]]]

print(arr1)

arr = np.zeros_like(arr1)
print(arr)
       

[[[1, 2, 3], [4, 5, 6]], [[5, 6, 7], [4, 7, 8]], [[2, 7, 9], [8, 0, 3]]]
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


In [15]:
#creating np.ones 

arr = np.ones((4,3),dtype=np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int16
2
12


In [25]:
arr = np.ones_like(arr1)
print(arr)
print(arr.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(3, 2, 3)


In [23]:
#np.empty
arr = np.empty((4,3),dtype=np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr.size)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int16
2
12


In [30]:
#np.full

arr = np.full((2,3),True)
print(arr)
print(arr.dtype)
print(arr.shape)

[[ True  True  True]
 [ True  True  True]]
bool
(2, 3)


In [31]:
arr = np.full((2,3),True) 

arr = np.full_like(arr1)
print(arr)

TypeError: full_like() missing 1 required positional argument: 'fill_value'